"""empty message

Revision ID: 218c34834ba7
Revises: 50e1894d83c3
Create Date: 2023-10-25 15:04:11.578804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218c34834ba7'
down_revision = '50e1894d83c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mileage', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('mileage')

    # ### end Alembic commands ###
