"""empty message

Revision ID: 50e1894d83c3
Revises: 666b01b5ee32
Create Date: 2023-10-24 13:59:09.355860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e1894d83c3'
down_revision = '666b01b5ee32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('g_auth_verify', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('g_auth_verify')

    # ### end Alembic commands ###
